### ISSUE TITLE
Crash in v0.0.9

### ISSUE THREAD

**Issue by dimkinware** [Crysis21/KeyboardHeightProvider#7]
From Crashlytics:

Fatal Exception: java.lang.IllegalStateException: windowInsets must not be null
       at com.hold1.keyboardheightprovider.KeyboardHeightProvider.getTopCutoutHeight(KeyboardHeightProvider.java:82)
       at com.hold1.keyboardheightprovider.KeyboardHeightProvider.computeKeyboardState(KeyboardHeightProvider.java:65)
       at com.hold1.keyboardheightprovider.KeyboardHeightProvider.access$computeKeyboardState(KeyboardHeightProvider.java:18)
       at com.hold1.keyboardheightprovider.KeyboardHeightProvider$getGlobalLayoutListener$1.onGlobalLayout(KeyboardHeightProvider.java:55)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2628)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by fpaaske** [comment]
I got this same issue with our NativeScript app. It happens when switching type of navigation bar (e.g. on pixel you can switch from 3-button, to 2-button and to gestures).

~~~
java.lang.IllegalStateException: windowInsets must not be null
	at com.hold1.keyboardheightprovider.KeyboardHeightProvider.getTopCutoutHeight(KeyboardHeightProvider.kt:82)
	at com.hold1.keyboardheightprovider.KeyboardHeightProvider.computeKeyboardState(KeyboardHeightProvider.kt:65)
	at com.hold1.keyboardheightprovider.KeyboardHeightProvider.access$computeKeyboardState(KeyboardHeightProvider.kt:18)
	at com.hold1.keyboardheightprovider.KeyboardHeightProvider$getGlobalLayoutListener$1.onGlobalLayout(KeyboardHeightProvider.kt:55)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2628)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
~~~
